export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// Sign in
export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START'
export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

// Sign Up
export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

// check user session
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION'

// Sign out
export const SIGNOUT_START = 'SIGNOUT_START'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE'
